### ISSUE TITLE
Experience with Mecool Bluetooth Remote (Remoter ATV3)

### ISSUE THREAD

**Issue by lmpina** [virresh/matvt#4]
Thank you for this mouse toggle app.

**Comment by virresh** [comment]
@lmpina thanks for your suggestions.

> A way to reduce scrolling speed would be most helpful.

Working on it. You'll get this option in the GUI in v1.02 😄 

> Many mouse clicks do not register

Thanks. I've seen this issue quite a few times as well. What I'm doing is simulating finger gestures instead of sending a click directly to android view (it's a very hard problem to determine the exact view to which the click should be sent since there can be millions of types of views).
I believe that wherever the scroll or clicks don't work is because the app might not support touch input properly. I will try to see what can be done about that, but would be great if someone can confirm this. I can't because on my Android TV, stuff works properly (and I only own one 😅 )

> Best boss key for use with this remote is 4, the return key.

Thanks, but I believe the latest version has an override option where you can set the return key to whatever you feel is appropriate.

> I can't imagine why anyone would want to take it out. Please leave it there!

Oh. I thought TDUK had linked the apk from releases section. I checked and he's uploaded a different apk on a mirror site, which is not the recommended way. His apk will obviously be outdated and not receive any improvements going forward, unless he's manually willing to update his APK on every app release.

Also to people who are downloading from mirrors, please do note **there's no guarantee that the app has not been modded**. I can't test the apk for the same, it's already hard to maintain so many OSS projects. I'll put this in Tech Doctor's notice but I don't think anything can be done about that.

**Comment by lmpina** [comment]
I believe that wherever the scroll or clicks don't work is 
because the app might not support touch input properly.

I doubt this is the case because G20 air mouse remotes with built-in 
mouse toggle work perfectly, in all cases where MATVT currently does 
not. The mouse pointer changes to a finger pointer when you're 
positioned over the hot spot. Mini keyboards also work perfectly. And, 
Fluxii MouseToggle-v1.5.2 works perfectly on all remotes having a play 
pause button. We just can't use the Fluxii app with Mecool Bluetooth 
remotes because they don't have a play/pause button. The alternate 
Vol-/Vol+ toggle Fluxii offers doesn't work on Mecool Bluetooth remotes, 
either. That's the vacancy hopefully MATVT can fill.

    Best boss key for use with this remote is 4, the return key. Thanks,
    but I believe the latest version has an override option where you
    can set the return key to whatever you feel is appropriate.

Yes, that feature is most welcome, but most people don't know how to 
identify alternate boss keys. That's why I mentioned that the return 
key, with ID=4, works best on this remote. Others that work on this 
remote are:

Override keys for use
with Mecool RemoterATV3

	
	
_Number_ 	_Lable_ 	_Notes_
3 	Home 	
4 	Return 	Works best!
19 	Up 	
20 	Down 	
21 	Left 	
22 	Right 	
23 	OK 	


And, for what it's worth, I was not able to get Vol-, Vol+ and Menu keys 
(on the Mecool Bluetooth remote/Remoter ATV3) to work at all with MATVT. 
Perhaps I was entering the wrong numbers...

My opinion: If MATVT could give Mecool box owners similar functionality 
to what Fluxii Mouse Toggle gave to FireTV Stick owners, it would be an 
amazing thing.

Thank you for developing this Virresh!

**Comment by virresh** [comment]
Thanks @lmpina for the additional details.

> I doubt this is the case because G20 air mouse remotes with built-in
mouse toggle work perfectly, in all cases where MATVT currently does
not.

So the difference here is kinda technical. There are two ways how input works. One is *simulate* a mouse by sending touch inputs wherever a mouse was expected. This approach uses things that were originally designed for helping disabled people, so apps that weren't built with accessibility in mind would run into compatibility trouble here.

The other is to actually create a mouse driver which is *registered within the system as an actual input method*. I'd expect this to work in all scenarios which were supported by code, because it's not limited by Android System's accessibility APIs. This has other limitations like more complicated installation mechanism (might require root access in some cases) and requires more folks / development effort. Being a individual maintainer, I don't think I can afford to spend this much time without any expectation. This is where MATVT cannot compete with paid alternatives unless enough folks show interest in open source code and support with their time / expertise. 

But once we have an active community willing to support the project, MATVT can grow at a much faster pace because it's much more open than any other closed alternative.




Also thanks for reporting the working remote buttons. I'll post these in a wiki sometime after MATVT gets more stable with a set of hardware's 😄

**Comment by virresh** [comment]
@lmpina 
I've updated the app with fixes for click control and release v1.0.3
Clicks should now work everywhere including home page and keyboards. Please report bugs if you come across any and close this issue if you feel this issue is solved.

Direct link - https://github.com/virresh/matvt/releases/download/v1.02/matvt-app-release-v1.02.apk

**Comment by lmpina** [comment]
I've updated the app with fixes for click control and release v1.0.3
     Clicks should now work everywhere including home page and 
keyboards. Please report bugs if you come across any and close this 
issue if you feel this issue is solved.

     Direct link - 
https://github.com/virresh/matvt/releases/download/v1.02/matvt-app-release-v1.02.apk 
<https://github.com/virresh/matvt/releases/download/v1.02/matvt-app-release-v1.02.apk>

_Scroll Mode Report, v1.02:_

Scroll mode is useful in this version. The ability to adjust scrolling 
speed is wonderful, but I can't help but wonder whether scroll mode and 
mouse mode should be combined. If scroll mode allowed mouse clicks why 
would the app even need two modes? One mode would certainly simplify 
things...

_Mouse Mode Report, v1.02:_

Keyboard clicks register occasionally in this version, meaning 
sometimes, intermittently, but still not consistently. I think there are 
two reasons for that.

First, here's a picture of Gboard, highest available version for Android 
7.x:

Here's the problem: D-Pad mode on RemoterATV3, the OEM/Mecool Bluetooth 
remote (supplied with Google Certified M8S Pro, KM3 Pro, KM9 Pro Android 
TV boxes), can not enter Gboard. D-Pad mode can't type a single 
character, so, there's no text search capability. D-Pad mode can't click 
the microphone icon, so there's no voice search capability. Sounds 
crazy, but even though these are official, Google-certified Android TV 
boxes, the OEM voice control remote does not work with the official 
Google keyboard. Sure, there are other on-screen keyboards that the OEM 
remote can enter, but none of them provide the all-important voice 
search function.

I would be great if MATVT could eventually solve that. At the moment:

1. When MATVT's mouse pointer is over Gboard, it generally disappears in 
4 seconds, which might not be long enough to register more than the 
first character of any word search. To prevent repeat characters, Gboard 
pauses between clicks and you have to type slowly. So, you're looking 
for a movie titled "Kingdom of Heaven". You may (key word = may) be able 
to enter the K with MATVT, but not the i, because the pointer times out. 
Eventually, you may be able to type the whole word, but it's currently a 
frustrating, tedious process. If you try it, you'll see what I mean.

Oddly enough, when MATVT's mouse pointer is over an app's left side drop 
down menu, it generally stays onscreen 10 seconds or so. Shouldn't mouse 
pointer sustain be consistent?

2. The aim/accuracy of the mouse pointer tip is currently way off. It's 
most accurate (but still not very good) at the smallest pointer size. 
It's less accurate (gets progressively worse) at the larger sizes. To 
verify, make the mouse pointer just one size larger than the smallest 
size and try (keyword = try) to search for "Kingdom of Heaven" again. 
Center the tip very carefully over the letter K, click, and observe that 
the letter I is entered. Note that I is the character directly above the 
letter K. That's how far the aim is off. To type a K, you've currently 
got to position the pointer tip over the letter m or over the 
exclamation point. If you try it, you'll see that this happens each and 
every time.

3. At the bottom of the keyboard there is a Status Bar. I use it all of 
the time. If you look carefully you'll see a G20 mouse pointer over the 
camera icon at the extreme left. I used a G20 remote to take this screen 
shot. Why didn't I use the OEM Bluetooth remote now that I have MATVT 
installed on the box? Because, even though permission to display over 
other apps has been granted, MATVT's mouse pointer still slides beneath 
the Status Bar. It currently can't click anything in that bar. It 
doesn't work very well on the upper Notification bar, either. IMHO, the 
ability to interact with these bars is far more important the screen 
wrap around currently implemented.

I hope these comments help and I hope that you don't take them in the 
wrong way. I appreciate what you've done and my only goal is to help 
make MATVT even better.

Thank you,

Lawrence Pina

**Comment by virresh** [comment]
Thanks for the detailed feedback @lmpina 
I highly appreciate every bit of information and it definitely helps out improve the mouse

I think your images didn't get attached along with your email
Can you edit your comment on github and add appropriate images?
I can't understand anything about cursor positions. Most likely this has something to do with system bar etc, but I am not sure. 

I'll get sometime over the weekend, so if you could add pictures before that, I'll try to see if I can simulate something similar

**Comment by lmpina** [comment]
On 3/11/2021 3:24 PM, Viresh Gupta wrote:
> I think your images didn't get attached along with your email
> Can you edit your comment on github and add appropriate images?

I've reattached a picture of the highest version of GBoard that can be 
installed on Mecool M8S Pro boxes having Android 7.x The OEM Bluetooth 
remote's Incompatibility with this keyboard is the problem. Right now, 
you need to use an aftermarket remote (mini keyboard, G10, G20) on these 
boxes (if you want to voice search for a movie within an app). DPad on 
the stock Mecool Bluetooth remote can't click that mic button. DPad on 
the stock Mecool Bluetooth remote can't even type the GBoard keys. MATVT 
currently has the timing and misalignment problems previously described. 
Mecool IR remotes with built-in mouse mode (picture attached) work 
perfectly. Aftermarket USB air mouse remotes work perfectly.

And here's something else to consider. If you toggle mouse mode ON using 
a Mecool IR remote, then DPad on the Mecool Bluetooth remote 
(RemoterATV3) does move the mouse pointer. Movement is exactly the same 
as if you were using the Mecool IR remote that turned it ON. So mouse 
mode does work on RemoterATV3. There's just no way to toggle it ON/OFF. 
That begs the question: How hard would it be to make a mouse toggle app 
with user configurable boss key who's sole purpose would be to toggle 
Mecool IR remote mouse mode ON/OFF using whatever driver has been 
preinstalled in firmware? That would solve the whole problem on these 
M8S Pro TV boxes! All you have to do is toggle mouse mode ON/OFF. The 
driver is already there (and it works perfectly)!

For MATVT marketing purposes, you should also know that there's a better 
version of GBoard that can be installed on Mecool KM3/9 boxes having 
Android 8+. MATVT wouldn't be needed to work with that version of GBoard 
because RemoterATV3's DPad can both type the keys and click the mic 
button. Problem is, few owners of Mecool KM3/9 TV boxes even know about 
that newer version of GBoard. I didn't find out about it until just 
recently. You still need mouse toggle on those boxes though, for 
compatibility with Internet browsers and apps like Ookla Speedtest.

**Comment by lmpina** [comment]
I thought more about the mouse toggle problem last night and it occurs 
to me that what's needed is a very simple Android app that captures and 
displays remote control key codes. Specifically, I would like to know:

1. What key code is generated when the built-in mouse toggle button on 
this Mecool IR remote is pressed?

2. What key code is generated when the Menu button on this Mecool voice 
control remote with built-in microphone is pressed?

Now with that info, wouldn't it be possible to remap a long press of the 
Menu button on the Bluetooth remote so that it sends the same code as 
the mouse button on the IR remote? If so, problem solved! That's all the 
Custom Mouse Toggle App for Mecool would have to do. Mouse mode already 
works, perfectly, there's just no way to turn it ON/OFF from the voice 
control remote. Even worse, there's no way to click any microphone 
buttons right now with the voice control remote. It's nuts with a capital N!

I'm thinking the menu button on the voice control remote might work 
better than the return button as the boss key because it's seldom used, 
especially when entering search text.

What do you think about this? It might be worth doing... Build a better 
mouse trap and the world will beat a path to your door!

**Comment by virresh** [comment]
@lmpina it's nice to have a discussion. I'm open to ideas, but first things first. 
I'll write in points so that hopefully you won't miss any.

1. I think you misunderstood my last reply. Please visit this discussion at https://github.com/virresh/matvt/issues/4 to understand what I mean by you images are not visible. When you reply on email, the images/any other content is simply stripped off due to security concerns. 

2. I would like to make it clear if it isn't already, this app is not my day job. I continue to develop it in my free time. I'm excited that it's helpful to people, and would like to continue develop it, but it will remain a side project which I do during free time (mostly on weekends)

3. There is no funding for this project, so there is nobody marketing it or anything ;)

4. This app is supposed to work on most standard Android TVs. To the best of my knowledge, the system cursor is not over-ridable without root access, which is why none of your suggestions would work. There simply is no system cursor that my (or for that matter any other app) can toggle without changes in firmware.

5. About your comment:
> wouldn't it be possible to remap a long press of the
> Menu button on the Bluetooth remote so that it sends the same code as
> the mouse button on the IR remote?

IR and bluetooth remotes work very differently. I see your point here, but I don't own one of these fancy remotes or the corresponding TV to be able to test, determine it's feasibility and implement this. If there's someone with the technical expertise to do it, I welcome them to have a peek into source code and contribute the required enhancement. We can talk all we want, but unless I have something I can test and try, I really can't do anything about it. I'm working in the total dark here.

6. You also questioned why do we need a mouse mode and a scroll mode seperately. Well, scrolling can be done anywhere in an app. Scroll mode is there to provide swipe input at the location of cursor. And how do you propose to move the cursor around if you remove the scroll mode? To the best of my understanding, your remote has way too few buttons than a standard full size remote. I have a Sony Android TV with a real full size remote, and I use MATVT without the need to go into scroll mode, because for me scrolling happens via color keys.
Here is a full size remote image just for your knowledge --
![image](https://user-images.githubusercontent.com/10978108/110975273-89c1ca80-8385-11eb-8764-cb58f5b83f96.png)



7. You mentioned that Fluxii's mouse toggle app works perfectly for you. May I ask you how you tested it? What key combinations in that work for you?







What I'd like from you:
- Can you enable viewing touch inputs on your TV? Official document of what I'm talking -- https://developer.android.com/studio/debug/dev-options#input . I'm pretty sure the mouse aim is as accurate as it can get. It's some other issue which you or some other Mecool KM3/9 TV box owner would have to investigate.
- It'd be even better if you can download the source code and debug the app. No worries if you can't. We can try and do guess work, but please bear with it.
- If possible, images that I can see somewhere.


Since there isn't any actionable on this issue, I'm leaving it for this week. Will get back to it when there's new developments.
