### ISSUE TITLE
Ko-fi

### ISSUE THREAD

**Issue by Mads** [virresh/matvt#59]
Noticed your post on zero count, decided to help move it to one and got this error.
Please fix ASAP :)

![2015CCEF-0827-4861-9A8C-D4EB04F6A072](https://user-images.githubusercontent.com/10404999/206281740-d4fa7fb1-7540-4f57-bb88-ae6d5ebd94bc.png)

**Comment by virresh** [comment]
Oh wow,

Thanks a lot @Mads for your contribution!

Earlier I was told by someone (in 2021) that they couldn't support via Buy Me a Coffee because of international payments not supported, and I discussed and settled upon opening a ko-fi account for this project as this one was widely used by folks internationally.

Seems like things have now changed, and while KoFi doesn't support international accounts, BuyMeACoffee does!
This is very valuable insight also, I'll shift all of my projects to use buy me a coffee. Your support is highly appreciated!
